### ISSUE TITLE
config file location?

### ISSUE THREAD

**Issue by slead** [Esri/geotrigger-ruby#2]
Can you please clarify the location of the config file mentioned at:

```
# reads config from ~/.geotrigger YAML :dev key
#
session = Geotrigger::Session.new config: :dev
```

Thanks

**Comment by kenichi** [comment]
@slead - on unix systems, `~` is shorthand for the current user's home directory. the actual code looks for the `.geotrigger` YAML file in `ENV['HOME']`, as you can see here:

https://github.com/Esri/geotrigger-ruby/blob/master/lib/geotrigger/session.rb#L69

on mac os x, that's usually `/Users/<username>`
unix/linux, `/home/<username>`
windows, `C:\Users\<username>` ( i think, i'm not sure about that one :smile: )

HTH - Thanks

**Comment by slead** [comment]
@kenichi thanks for the response. Would it make more sense to put this under `config/geotrigger.yml`? 

(I'm not expert enough at Rails to make that change in your gem and bundle it, etc)

Thanks

**Comment by slead** [comment]
I worked around this using:

```
# under /config/environments/development.rb
config.geotrigger_client_id = 'abcde'
config.geotrigger_client_secret = '123456'

# in my app
session = Geotrigger::Session.new client_id: Rails.application.config.geotrigger_client_id, client_secret: Rails.application.config.geotrigger_client_secret
```

I'd be keen to know if there's a better way to centralize the credentials in a Rails app. Thanks for writing this BTW!

**Comment by kenichi** [comment]
@slead you're very welcome! hmmm, i'm not quite sure where to make it most convenient in rails - i haven't used rails since 2.3 days...

@jwieringa @ajturner do you have any ideas on the above question?

**Comment by ajturner** [comment]
@slead here are some tips for managing private keys/tokens by environment: http://railsapps.github.io/rails-environment-variables.html

Depends also on where and how you deploy - Heroku can easily configure environment variables.

I've used Figaro
